GioSalcedo/figo-v1

- app/controllers/bankings_controller.rb
- app/views/bankings/create.html.erb
- app/views/bankings/destroy.html.erb
- app/views/bankings/edit.html.erb
- app/views/bankings/index.html.erb
- app/views/bankings/new.html.erb
- app/views/bankings/show.html.erb
- app/views/bankings/update.html.erb
- config/routes.rb
- test/controllers/bankings_controller_test.rb
create controller trasnferencias proyect FIGO, revised plis
> create controller transferencias

- app/controllers/business_controller.rb
- test/controllers/business_controller_test.rb
business controller has been created, please check it out.
> controlador productos creado

- app/controllers/accounts_controller.rb
- app/views/accounts/create.html.erb
- app/views/accounts/destroy.html.erb
- app/views/accounts/edit.html.erb
- app/views/accounts/index.html.erb
- app/views/accounts/new.html.erb
- app/views/accounts/show.html.erb
- app/views/accounts/update.html.erb
- config/routes.rb
- test/controllers/accounts_controller_test.rb
creacion de account controller
> account controller

- app/controllers/accounts_controller.rb
codie el controlador de las cuentas
> account controller coding

- app/controllers/savings_controller.rb
> account controller coding correciones

- app/controllers/bankings_controller.rb
- app/controllers/savings_controller.rb
> creación logica controller

- app/controllers/debts_controller.rb
> debts coding

- app/controllers/application_controller.rb
- app/controllers/earnings_controller.rb
- app/controllers/egresses_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/savings_controller.rb
Nuevos cambios a nivel de controlador
> Controllers config devise

- app/assets/stylesheets/pages/_home.scss
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> some views users

- app/controllers/businesses_controller.rb
- app/views/businesses/business_params.html.erb
- app/views/businesses/destroy.html.erb
- app/views/businesses/edit.html.erb
- app/views/businesses/index.html.erb
- app/views/businesses/new.html.erb
- app/views/businesses/set_business.html.erb
- app/views/businesses/show.html.erb
- app/views/businesses/update.html.erb
- config/routes.rb
- test/controllers/business_controller_test.rb
- test/controllers/businesses_controller_test.rb
Configuración del controlador arreglada
> corrección de controller businesses

- app/controllers/bankings_controller.rb
- app/views/pages/home.html.erb
> arreglo btn sesion

- app/controllers/budgets_controller.rb
- app/controllers/businesses_controller.rb
- app/controllers/debts_controller.rb
- app/controllers/savings_controller.rb
- app/models/user.rb
- app/views/budgets/_form.html.erb
- app/views/budgets/edit.html.erb
- app/views/budgets/index.html.erb
- app/views/budgets/new.html.erb
- app/views/budgets/show.html.erb
- app/views/businesses/show.html.erb
- app/views/debts/_form.html.erb
- app/views/debts/index.html.erb
- app/views/debts/show.html.erb
- app/views/savings/_form.html.erb
- app/views/savings/edit.html.erb
- app/views/savings/index.html.erb
- app/views/savings/new.html.erb
- app/views/savings/show.html.erb
- config/routes.rb
> Logic basic done

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/bankings_controller.rb
- app/views/bankings/_form.html.erb
> add dotenv-rails

- app/views/bankings/index.html.erb
- app/views/pages/home.html.erb
> Ultimos cambios

- app/assets/stylesheets/pages/_home.scss
- app/javascript/application.js
- app/views/devise/sessions/new.html.erb
- db/seeds.rb
> estilos forumulario previo

- app/views/accounts/edit.html.erb
- app/views/accounts/index.html.erb
- app/views/accounts/new.html.erb
- app/views/accounts/show.html.erb
- app/views/bankings/index.html.erb
- app/views/budgets/edit.html.erb
- app/views/shared/_aside.html.erb
- app/views/shared/_dashboard.html.erb
Estilos basicos instyalados en todas las vistas de nuevas cuentas
> estilos basicos instalados

- app/views/bankings/new.html.erb
- app/views/shared/_dashboard.html.erb
> dumy table

- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
> pageloginfalla

- app/assets/stylesheets/pages/_home.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_dashboard.html.erb
> Revert "pageregistresfinish"

- app/javascript/application.js
- app/views/budgets/index.html.erb
- app/views/businesses/show.html.erb
> estilo premlimina}r para los index

- app/views/shared/_aside.html.erb
- config/routes.rb
> logic done

- app/views/budgets/show.html.erb
- app/views/businesses/show.html.erb
> estilo premliminar para los show

- db/seeds.rb
seed moidificada con la info modificada segun la modificacion sugerida.
> seed modificada

- app/assets/stylesheets/pages/_home.scss
- app/views/accounts/_form.html.erb
- app/views/accounts/new.html.erb
- app/views/budgets/index.html.erb
- app/views/businesses/_form.html.erb
- app/views/businesses/show.html.erb
- app/views/debts/index.html.erb
- app/views/debts/show.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/earnings/_form.html.erb
- app/views/earnings/show.html.erb
- app/views/egresses/_form.html.erb
- app/views/egresses/show.html.erb
- app/views/savings/index.html.erb
- app/views/savings/show.html.erb
- app/views/shared/_aside.html.erb
> retoques de ultimo recorrido

- .gitignore
- app/assets/stylesheets/pages/_welcome.scss
- app/views/shared/_welcome.html.erb
> ultimitos para el 99

- app/assets/stylesheets/pages/_home.scss
- app/views/bankings/_form.html.erb
- app/views/budgets/index.html.erb
- app/views/debts/index.html.erb
- app/views/layouts/home.html.erb
- app/views/savings/index.html.erb
- db/schema.rb
tildes como si no hubiera un mañana y la verdad es que no lo hay
> tildes como si no hubiera un mañana... y la verdad es que no lo hay
